version: "3.8"
services:
  postgres-db:
    container_name: WarehouseSimulator
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: WarehouseSimulator
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5455:5432"

volumes:
  postgresql_data:
    driver: local