CREATE TABLE character_entity
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_name  VARCHAR(255),
    character_class VARCHAR(255),
    health          INTEGER,
    mana            INTEGER,
    attack          INTEGER,
    defense         INTEGER,
    account_id      BIGINT,
    CONSTRAINT pk_characterentity PRIMARY KEY (id)
);

ALTER TABLE character_entity
    ADD CONSTRAINT uc_characterentity_account UNIQUE (account_id);

ALTER TABLE character_entity
    ADD CONSTRAINT FK_CHARACTERENTITY_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account_entity (id);