CREATE TABLE chat_entity
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_name VARCHAR(255),
    message        VARCHAR(255),
    CONSTRAINT pk_chatentity PRIMARY KEY (id)
);